[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eventshow"
version = "0.0.1"
authors = [
  { name="Runiku Boa", email="bao@robot.t.u-tokyo.ac.jp" },
]
description = "framerize and visualize event raw data"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
eventshow = "eventshow:__main__.main"
